#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Dec 30 10:58:23 2012

from wxPython.wx import *

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.combo_box_1 = wxComboBox(self, -1, choices=["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360"], style=wxCB_DROPDOWN)
        self.radio_box_9 = wxRadioBox(self, -1, "radio_box_9", choices=["Forward Left", "Left", "Back Left", "None"], majorDimension=0, style=wxRA_SPECIFY_ROWS)
        self.radio_box_10 = wxRadioBox(self, -1, "radio_box_10", choices=["Forward", "Stop", "Back"], majorDimension=0, style=wxRA_SPECIFY_ROWS)
        self.radio_box_11 = wxRadioBox(self, -1, "radio_box_11", choices=["Forward Right", "Right", "Back Right", "None"], majorDimension=0, style=wxRA_SPECIFY_ROWS)
        self.panel_1 = wxScrolledWindow(self, -1, style=wxTAB_TRAVERSAL)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("GUI for Rover")
        self.SetSize((493, 659))
        self.combo_box_1.SetMinSize((189, 29))
        self.combo_box_1.SetSelection(0)
        self.radio_box_9.SetSelection(0)
        self.radio_box_10.SetSelection(0)
        self.radio_box_11.SetSelection(0)
        self.panel_1.SetMinSize((493, 218))
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        grid_sizer_3 = wxGridSizer(1, 3, 0, 0)
        sizer_1.Add(self.combo_box_1, 0, wxALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_3.Add(self.radio_box_9, 0, 0, 0)
        grid_sizer_3.Add(self.radio_box_10, 0, 0, 0)
        grid_sizer_3.Add(self.radio_box_11, 0, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wxEXPAND, 0)
        sizer_1.Add(self.panel_1, 1, wxEXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame1

class MyFrame3(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame3.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.StartButton = wxButton(self, -1, "Start")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame3.__set_properties
        self.SetTitle("frame_4")
        self.SetSize((274, 77))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame3.__do_layout
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_2.Add(self.StartButton, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MyFrame3
class RoboGui(wxApp):
    def OnInit(self):
        wxInitAllImageHandlers()
        StartingFrame = MyFrame1(None, -1, "")
        self.SetTopWindow(StartingFrame)
        StartingFrame.Show()
        return 1

# end of class RoboGui

if __name__ == "__main__":
    RoboticsApp = RoboGui(0)
    RoboticsApp.MainLoop()
