#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Dec 30 10:58:23 2012, then painstakingly hand-edited

import wx

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.combo_box_1 = wx.ComboBox(self, -1, choices=["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250", "260", "270", "280", "290", "300", "310", "320", "330", "340", "350", "360"], style=wx.CB_DROPDOWN)
        self.radio_box_9 = wx.RadioBox(self, -1, "Left Movement", choices=["Forward Left", "Left", "Back Left", "None"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_10 = wx.RadioBox(self, -1, "Foward Movement", choices=["Forward", "Stop", "Backward"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.radio_box_11 = wx.RadioBox(self, -1, "Right Movement", choices=["Forward Right", "Right", "Back Right", "None"], majorDimension=0, style=wx.RA_SPECIFY_ROWS )
        self.radio_box_9.SetBackgroundColour("White")
        self.radio_box_10.SetBackgroundColour("White")
        self.radio_box_11.SetBackgroundColour("White")
        self.panel_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL | wx.RAISED_BORDER)
        self.quote = wx.StaticText(self.panel_1, label="Diagram of rover goes here \n(with dynamically moving wheels and such)", pos=(20, 30))

        menubar = wx.MenuBar()
        file = wx.Menu()
        
        file.Append(105, '&Quit\tCtrl+Q', 'Leave this place!')
        menubar.Append(file, '&File')
        self.SetMenuBar(menubar)
        self.Center()
        self.CreateStatusBar()
        self.Bind(wx.EVT_MENU, self.OnQuit, id=105)
		
        self.__set_properties()
        self.__do_layout()
        # end wxGlade
		
    def OnQuit(self, event):
        self.Close()

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Rover Drive")
        self.SetSize((493, 400))
        self.combo_box_1.SetMinSize((189, 29))
        self.combo_box_1.SetSelection(0)
        self.radio_box_9.SetSelection(0)
        self.radio_box_10.SetSelection(0)
        self.radio_box_11.SetSelection(0)
        self.panel_1.SetMinSize((493, 218))
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_3.Add(self.radio_box_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.radio_box_10, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.radio_box_11, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4.Add(self.combo_box_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_4.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame1

class MyFrame3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame3.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.StartButton = wx.Button(self, -1, "Start")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame3.__set_properties
        self.SetTitle("frame_4")
        self.SetSize((274, 77))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame3.__do_layout
        sizer_2 = wx.BoxSizer(wxVERTICAL)
        sizer_2.Add(self.StartButton, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MyFrame3
class RoboGui(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        StartingFrame = MyFrame1(None, -1, "")
        self.SetTopWindow(StartingFrame)
        StartingFrame.Show()
        return 1

# end of class RoboGui

if __name__ == "__main__":
    RoboticsApp = RoboGui(0)
    RoboticsApp.MainLoop()