                #!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Dec 30 10:58:23 2012, then painstakingly hand-edited

import wx

class DriveControls(wx.Panel):
    def __init__(self, parent):
        
        wx.Panel.__init__(self, parent=parent, id=wx.ID_ANY, size=(320,250))
        
        self.slider = wx.Slider(self, value=0, minValue=0, maxValue=360, size=(80, -1), style=wx.SL_HORIZONTAL)
        
        self.slider.Bind(wx.EVT_SCROLL, self.DisplaySliderValue)
        
        self.txtCtrlSlider = wx.TextCtrl(self, value="0", size=(50, -1))

        self.txtCtrlSlider.Bind(wx.EVT_TEXT, self.ChangeSliderValue)

        self.rbLeft = wx.RadioBox(self, -1, "Left Movement",
                                  choices=["Forward Left", "Left", "Back Left", "None"],
                                  majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        
        self.rbForward = wx.RadioBox(self, -1, "Forward Movement",
                                     choices=["Forward", "Stop", "Backward"],
                                     majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        
        self.rbRight = wx.RadioBox(self, -1, "Right Movement",
                                   choices=["Forward Right", "Right", "Back Right", "None"],
                                   majorDimension=0, style=wx.RA_SPECIFY_ROWS )
        
        self.rbLeft.SetBackgroundColour("White")
        self.rbForward.SetBackgroundColour("White")
        self.rbRight.SetBackgroundColour("White")

        self.stSlider = wx.StaticText(self, label="Slider")
        
        self.Center()
        self.__set_properties()
        self.__do_layout()

    def DisplaySliderValue(self, event):
        obj = event.GetEventObject()
        value = obj.GetValue()

        self.txtCtrlSlider.ChangeValue(str(value))

    def ChangeSliderValue(self, event):
        value = event.GetString()

        self.slider.SetValue(int(value))

    def __set_properties(self):

        self.rbLeft.SetSelection(0)
        self.rbForward.SetSelection(0)
        self.rbRight.SetSelection(0)

    def __do_layout(self):
        sizer = wx.GridBagSizer(3, 3)
        
        sizer.Add(self.slider, (2, 2))

        sizer.Add(self.txtCtrlSlider, (2, 3))

        sizer.Add(self.stSlider, (1, 2), span=(1, 2), flag=wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL)

        sizer.Add(self.rbLeft, (4, 1))
        sizer.Add(self.rbForward, (0, 1), span=(4, 1))
        sizer.Add(self.rbRight, (4, 2), span=(1, 2))
        
        self.SetSizer(sizer)
        self.Layout()

