                #!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Dec 30 10:58:23 2012, then painstakingly hand-edited

import wx
import math

class DriveControls(wx.Panel):
    def __init__(self, parent, driveSim, roverStatus):

        wx.Panel.__init__(self, parent=parent, id=wx.ID_ANY, size=(320, 250), style=wx.BORDER_SUNKEN)

        self.parent = parent

        self.driveSim = driveSim

        titleFont = wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD)

        self.Bind(wx.EVT_PAINT, self.OnPaint)

        self.roverStatus = roverStatus

        self.throttle = wx.Slider(self, value=self.roverStatus.throttle, minValue=-100, maxValue=100, size=(200, -1), style=wx.SL_HORIZONTAL)
        self.angle = wx.Slider(self, value=math.degrees(self.roverStatus.angle), minValue=-90, maxValue=90, size=(200, -1), style=wx.SL_HORIZONTAL)

        self.throttle.Bind(wx.EVT_SCROLL, self.ChangeThrottleValue)
        self.angle.Bind(wx.EVT_SCROLL, self.ChangeAngleValue)

        self.spinCtrlThrottle = wx.SpinCtrl(self, value="%d" % self.roverStatus.throttle, size=(55, -1))
        self.spinCtrlThrottle.SetRange(-100, 100)
        self.spinCtrlThrottle.Bind(wx.EVT_SPINCTRL, self.ChangeThrottleValue)
        
        self.spinCtrlAngle = wx.SpinCtrl(self, value="%d" % math.degrees(self.roverStatus.angle), size=(55, -1))
        self.spinCtrlAngle.SetRange(-90, 90)
        self.spinCtrlAngle.Bind(wx.EVT_SPINCTRL, self.ChangeAngleValue)
        
        self.zeroPtTurn = wx.Button(self, label="Zero Point Turn")
        self.zeroPtTurn.Bind(wx.EVT_BUTTON, self.ZeroPtTurn)
        
        self.stDriveControls = wx.StaticText(self, label="Drive Controls")
        self.stDriveControls.SetFont(titleFont)
        self.stThrottle = wx.StaticText(self, label="Throttle")
        self.stAngle = wx.StaticText(self, label="Angle")
        
        self.Center()
        self.__do_layout()

    def OnPaint(self, event):
        self.spinCtrlThrottle.SetValue(self.roverStatus.throttle)
        self.throttle.SetValue(self.roverStatus.throttle)
        self.spinCtrlAngle.SetValue(-math.degrees(self.roverStatus.angle))
        self.angle.SetValue(-math.degrees(self.roverStatus.angle))

    def ChangeThrottleValue(self, event):
        obj = event.GetEventObject()
        print obj.GetValue()
        self.roverStatus.throttle = obj.GetValue()

        self.spinCtrlThrottle.SetValue(self.roverStatus.throttle)
        self.throttle.SetValue(self.roverStatus.throttle)
        self.parent.Refresh()
        self.driveSim.Refresh()

    def ChangeAngleValue(self, event):
        obj = event.GetEventObject()
        self.roverStatus.SetAngle(-obj.GetValue())

        self.spinCtrlAngle.SetValue(-math.degrees(self.roverStatus.angle))
        self.angle.SetValue(-math.degrees(self.roverStatus.angle))

        self.parent.Refresh()

    def ZeroPtTurn(self, event):
        print("Zero Point Turn")

    def __do_layout(self):
        sizer = wx.GridBagSizer(3, 3)
        
        sizer.Add(self.stDriveControls, (0, 0), span=(2, 3), flag=wx.ALIGN_CENTER)
        
        sizer.Add(self.throttle, (5, 1))
        sizer.Add(self.spinCtrlThrottle, (5, 2))
        sizer.Add(self.stThrottle, (4, 1), flag=wx.ALIGN_CENTER)

        sizer.Add(self.angle, (3, 1))
        sizer.Add(self.spinCtrlAngle, (3, 2))
        sizer.Add(self.stAngle, (2, 1), flag=wx.ALIGN_CENTER)
        
        sizer.Add(self.zeroPtTurn, (7, 1), flag=wx.EXPAND)
        
        self.SetSizer(sizer)
        self.Layout()
