                #!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sun Dec 30 10:58:23 2012, then painstakingly hand-edited

import wx

class DriveControls(wx.Panel):
    def __init__(self, parent):
        
        wx.Panel.__init__(self, parent=parent, id=wx.ID_ANY, size=(320,250), style=wx.BORDER_SUNKEN)
        
        titleFont = wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD)
        
        self.throttle = wx.Slider(self, value=100, minValue=0, maxValue=100, size=(200, -1), style=wx.SL_HORIZONTAL)
        self.angle = wx.Slider(self, value=0, minValue=-90, maxValue=90, size=(200, -1), style=wx.SL_HORIZONTAL)

        self.throttle.Bind(wx.EVT_SCROLL, self.DisplayThrottleValue)
        self.angle.Bind(wx.EVT_SCROLL, self.DisplayAngleValue)

        self.spinCtrlThrottle = wx.SpinCtrl(self, value="100", size=(55, -1))
        self.spinCtrlThrottle.SetRange(0, 100)
        self.spinCtrlThrottle.Bind(wx.EVT_SPINCTRL, self.ChangeThrottleValue)
        
        self.spinCtrlAngle = wx.SpinCtrl(self, value="0", size=(55, -1))
        self.spinCtrlAngle.SetRange(-90, 90)
        self.spinCtrlAngle.Bind(wx.EVT_SPINCTRL, self.ChangeAngleValue)
        
        self.zeroPtTurn = wx.Button(self, label="Zero Point Turn")
        self.zeroPtTurn.Bind(wx.EVT_BUTTON, self.ZeroPtTurn)
        
        self.stDriveControls = wx.StaticText(self, label="Drive Controls")
        self.stDriveControls.SetFont(titleFont)
        self.stThrottle = wx.StaticText(self, label="Throttle")
        self.stAngle = wx.StaticText(self, label="Angle")
        
        self.Center()
        self.__do_layout()

    def DisplayThrottleValue(self, event):
        obj = event.GetEventObject()
        value = obj.GetValue()

        self.spinCtrlThrottle.SetValue(value)

    def DisplayAngleValue(self, event):
        obj = event.GetEventObject()
        value = obj.GetValue()

        self.spinCtrlAngle.SetValue(value)
    
    def ChangeThrottleValue(self, event):
        obj = event.GetEventObject()
        value = obj.GetValue()

        self.throttle.SetValue(value)

    def ChangeAngleValue(self, event):
        obj = event.GetEventObject()
        value = obj.GetValue()

        self.angle.SetValue(value)
    
    def ZeroPtTurn(self, event):
        print("Zero Point Turn")

    def __do_layout(self):
        sizer = wx.GridBagSizer(3, 3)
        
        sizer.Add(self.stDriveControls, (0, 0), span=(2, 3), flag=wx.ALIGN_CENTER)
        
        sizer.Add(self.throttle, (5, 1))
        sizer.Add(self.spinCtrlThrottle, (5, 2))
        sizer.Add(self.stThrottle, (4, 1), flag=wx.ALIGN_CENTER)

        sizer.Add(self.angle, (3, 1))
        sizer.Add(self.spinCtrlAngle, (3, 2))
        sizer.Add(self.stAngle, (2, 1), flag=wx.ALIGN_CENTER)
        
        sizer.Add(self.zeroPtTurn, (7, 1), flag=wx.EXPAND)
        
        self.SetSizer(sizer)
        self.Layout()
